medicalSite/blog/urls.py
from django.urls import path
from . import views
app_name='blog'

urlpatterns=[
    path('',views.index, name='blog'),
    path('post/<str:slug>', views.blog_post, name="blog_post")
]

medicalSite/clinics/urls.py
from django.urls import path
from . import views
app_name='clinics'

urlpatterns=[
    path('add-clinic/',views.add_clinic, name="clinics_add_clinic"),
    path("clinic", views.search_clinic, name="clinics_search"),
    path('treatments/', views.treatments, name="clinic_treatments"),
    path("destinations", views.destinations, name="clinic_destinations"),
    path("destinations/<str:search_country>", views.destinations, name="clinic_destinations"),
    path("destinations/<str:search_country>/<str:search_city>", views.destinations, name="clinic_destinations"),

    path('free-quote/', views.get_free_quote, name= "free_quote_without_clinic"),
    path('<slug:clinic_slug>/', views.get_each_clinic, name= "clinics_each_detail"),
    path('<slug:clinic_slug>/add-review', views.get_reviews, name= "clinics_reviews"),
    path("clinic/<str:search_treatment>", views.search_clinic, name="clinics_search"),
    path("clinic/<str:search_treatment>/<str:search_country>", views.search_clinic, name="clinics_search"),
    path("clinic/<str:search_treatment>/<str:search_country>/<str:search_city>", views.search_clinic, name="clinics_search"),
    path("rankings/<str:category>", views.rankings, name="clinics_rankings"),
    path("rankings/<str:category>/<str:country>", views.rankings, name="clinics_rankings"),
    path("rankings/<str:category>/<str:country>/<str:city>", views.rankings, name="clinics_rankings"),
    path('run-interval', views.run_interval, name="run_interval"),
]

medicalSite/medicalSite/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from django.conf.urls.i18n import i18n_patterns

#local imports
from . import settings
from . import views


urlpatterns = [
    path('admin/', admin.site.urls),
    path('tinymce/', include('tinymce.urls')),
    path('i18n/', include('django.conf.urls.i18n')),
    path('change-currency/', views.change_currency, name= 'change_currency'),
    path('create-slug/', views.create_slug, name='create_slug'),
    path('exists-in-treatments/', views.exists_in_treatments, name='exists_in_treatments'),
    path('show-error', views.show_error, name='show_error'),
    path('set-in-session/', views.setInSession, name="set_in_session")
]

urlpatterns += i18n_patterns(
    path('', views.Home, name= 'home'),
    path('blog/', include("blog.urls"), name="blog"),
    path('contact/', views.Contact, name= 'contact'),
    path('about-us/', views.About, name= 'about'),
    path('sitemap/', views.Sitemap, name= 'sitemap'),
    path('terms-and-conditions/', views.TermsAndConditions, name= 'terms_and_conditions'),
    path('ajax_calls/search/', views.autocompleteModel),
    path('ajax_calls/country/search/', views.autocompleteCountryModel),
    path('', include("clinics.urls"), name="clinics"),
    prefix_default_language=False
)
handler404 = 'medicalSite.views.error_404'
handler500 = 'medicalSite.views.error_500'

if settings.DEBUG:
    urlpatterns+=static(settings.MEDIA_URL,document_root=settings.MEDIA_ROOT)

medicalSite/blog/models.py
from django.db import models
from django.utils.text import slugify
from tinymce.widgets import TinyMCE

from clinics.models import Language

from unidecode import unidecode

from slugify import slugify

# Create your models here.
class BlogPost(models.Model):
    title = models.CharField(max_length=250)
    about = models.CharField(max_length=250, null=True)
    meta_description = models.CharField(max_length=250, null=True)
    language = models.ForeignKey(Language, on_delete=models.CASCADE, related_name='bloglanguage', blank= True, null=True)
    slug = models.SlugField(max_length=250, unique=True, null=True, blank=True, allow_unicode=True)
    cover_img = models.ImageField(upload_to='blog/')
    author = models.CharField(max_length=250, null= True)
    content = models.TextField()
    timestamp = models.DateTimeField(auto_now=True)

    def save(self, *args, **kwargs):
        self.slug = slugify(self.title)
        super(BlogPost, self).save(*args, **kwargs)

    def __str__(self):
        # sort by date
        return self.title


class BlogContact(models.Model):
    name = models.CharField(max_length=250, blank= False, null= False)
    phone_code = models.CharField(max_length= 256, blank= True, null= True)
    phone_no = models.CharField(max_length= 256, blank= True, null= True)
    email = models.CharField(max_length= 256, blank= False, null= False)
    comment = models.TextField(blank= False, null= False)
    created= models.DateTimeField(auto_now=True)
    is_seen  = models.BooleanField(default= False)
    
    class Meta:
        ordering=('-created',)
        verbose_name_plural='Blog Contact'

    def __str__(self):
        return str(self.name)

medicalSite/blog/views.py
from django.shortcuts import render, redirect

from clinics.models import Country, Language
from .models import BlogPost, BlogContact
from django.core.paginator import Paginator
from django.contrib import messages
from urllib.parse import unquote

# Create your views here.

def index(request):
    posts = BlogPost.objects.filter(language__code=request.LANGUAGE_CODE).all().order_by('-timestamp')
    # pagination
    paginator = Paginator(posts, 10)
    page_no = request.GET.get('page', 1)
    current_page = paginator.page(page_no)

    # context
    context = {
        'posts': current_page.object_list,
        "paginator": paginator,
        "current_page": current_page,
        "page_no": page_no,
    }
    return render(request, 'blog/index.html', context)


def blog_post(request, slug):
    slug = unquote(slug)
    post = BlogPost.objects.get(slug=slug)
    countries = Country.objects.filter(language=Language.objects.get(code=request.LANGUAGE_CODE)).reverse()

    if request.method == "POST":
        comment = request.POST.get('comment')
        name = request.POST.get('name')
        email = request.POST.get('email')
        phone_code = request.POST.get("phone_code")
        phone_no = request.POST.get('phone_no')
        blogcontact_instance= BlogContact.objects.create(name = name, email=email, phone_code=phone_code, phone_no=phone_no, comment = comment)
        blogcontact_instance.save()
        if request.LANGUAGE_CODE == "fr":
            messages.success(request, "Votre message a été envoyé avec succès.")
        else:
            messages.success(request, "Your message has been sent successfully.")
        return redirect(request.path_info)

    context = {
        'post': post,
        "all_countries": countries
    }
    
    return render(request, 'blog/post.html', context)

medicalSite/templates/blog/index.html
{% extends 'main/base.html' %} {% load static %}
{% load i18n %}

{% block title %}{% trans "Blog on medical tourism: Dental, hair transplant and plastic surgery" %} - MyTripMed{% endblock title %} 
{% block description %}{% trans "Find the best deals for your medical abroad journey and the Top destinations." %} - MyTripMed{% endblock description %}

{% block body %}
<section class="top-section blog-header">
  <div class="container">
    <h1>{% trans "The latest news on medical tourism and our advice for your next treatment." %}</h1>
    <div class="blog-bg"></div>
  </div>
</section>
<div class="container">
  <h3 class="text-dark heading-border">{% trans "Recent Posts" %}</h3>
  <div class="row my-5">
    {% for post in posts %}
    <div class="col-sm-6">
      <div class="blog-card">
        <a href="{% url 'blog:blog_post' post.slug %}"><img src="{{ post.cover_img.url }}" alt="blog-1" class="blog-image"></a>
        <div class="blog-content">
          <h5><a href="{% url 'blog:blog_post' post.slug %}" style="color: #473198 !important; font-size: 1.9rem; letter-spacing: normal !important;">{{ post.title }}</a></h5>
          <p class="p-sm">
            {{ post.about }}
          </p>
          <div class="d-grid gap-2 d-md-flex justify-content-end pt-5">
            <a class="btn btn-sm btn-primary" href="{% url 'blog:blog_post' post.slug %}" type="button">{% trans "See More" %}</a>
          </div>
        </div>
      </div>
    </div>
    {% endfor %}

  </div>
        
  <div class="pagination">
    <nav aria-label="Results Navigation" class="w-100">
        <ul class="pagination justify-content-center">
            <li class="page-item">
                {% if current_page.has_previous %}
                <a class="btn-icon" href="{% url 'blog:blog' %}?page={{page_no|add:"-1"}}" tabindex="-1" aria-disabled="true">
                    <i class="text-dark" data-feather="chevron-{% if LANGUAGE_BIDI %}right{% else %}left{% endif %}"></i>
                </a>
                {% else %}
                <a class="btn-icon disabled" href="#" tabindex="-1" aria-disabled="true">
                    <i class="text-dark" data-feather="chevron-{% if LANGUAGE_BIDI %}right{% else %}left{% endif %}"></i>
                </a>
                {% endif %}
            </li>
            <li class="page-item active">

                <h5 class="pagination-text">
                    {% trans "Page" %} {{page_no}} {% trans "of" %} {{ paginator.num_pages }}
                </h5>

            </li>
            <li class="page-item">
                {% if current_page.has_next %}
                <a class="btn-icon" href="{% url 'blog:blog' %}?page={{page_no|add:"+1"}}">
                    <i class="text-dark" data-feather="chevron-{% if LANGUAGE_BIDI %}left{% else %}right{% endif %}"></i>
                </a>
                {% else %}
                <a class="btn-icon disabled" href="#">
                    <i class="text-dark" data-feather="chevron-{% if LANGUAGE_BIDI %}left{% else %}right{% endif %}"></i>
                </a>
                {% endif %}
            </li>
        </ul>
    </nav>
</div>
      </div>
    </div>
  </div>

  {% endblock body %}
</div>

medicalSite/templates/blog/post.html
{% extends 'main/base.html' %} {% load static %}
{% load i18n %}
 {% block title %}{{ post.title }} - MyTripMed{% endblock title %} {% block body %}
 {% block description %}{{ post.meta_description }}{% endblock description %}

 <style>
  @media screen and (max-width: 768px) {
    #blog-title-container {
      width: 100% !important;
    }
    #blog-title-container h1 {
      text-align: center !important;
    }

    #blog-img {
      padding: 8px 10px !important; 
    }
  }
  td {
    border-width: 0.5px !important;
    font-size: 1.6rem !important;
  }
    
 </style>
<section class="top-section hero-section">
  <div class="container">
    <div class="col-8" id="blog-title-container">
      <h1>{{ post.title }}</h1>
    </div>
    <div class="blog-bg"></div>
  </div>
</section>

<div class="container">
  <div class="blog-section">
    <div class="row">
      <div class="col-lg-8 col-md-10 container-border container-border-left">
        <section class="blog-top pb-0">
          <div class="d-flex justify-content-between heading-border">
            <div class="icon-text icon-text-big">
              <img src="{% static "img/pencil-icon.png" %}" alt="pencil-icon" >
              <span>{{ post.author }}</span>
            </div>
            <p class="p-big">{{ post.timestamp|date:"j F o" }}</p>
          </div>
        </section>
        <div style="padding: 40px 50px" id="blog-img">
          <img
            src="{{ post.cover_img.url }}"
            style="
              border-radius: 20px;
              box-shadow: rgba(0, 0, 0, 0.24) 0px 3px 8px;
            "
            class="w-100"
          />
        </div>

        <section class="blog-content-text pt-0">
          {{ post.content|safe }}
        </section>
      </div>
      <div class="col-lg-4 container-border container-border-right">
        <div class="card card-sm card-border mb-5">
          <h5>{% trans "Get a free quote" %}</h5>

          <form method="POST" action="">
            {% csrf_token %}
          <div class="pt-4">
            <div class="form-group mb-4">
              <label for="request-name" class="form-label">{% trans "Name" %}*</label>
              <input type="text" class="form-input" id="request-name"
              placeholder="{% trans "Name" %}" aria-label="Your name" name="name" required>
            </div>
            <div class="form-group mb-4">
              <label for="request-email" class="form-label">{% trans "Email Address" %}*</label>
              <input type="email" class="form-input" id="request-email"
              placeholder="{% trans "Email" %}" aria-label="Your name" name="email" required>
            </div>
            <div class="form-group mb-4">
              <label for="request-email" class="form-label">{% trans "Phone Number" %} <b>({% trans "optional" %})</b></label>
              <div class="row">

                <div class="col-4">
                  <select class="form-select" id="code1" name="phone_code">
                    {% for country in all_countries %}
                    <option data-countryCode={{country.name}} value={{country.phone_code}}>{{country.name}} ({{country.phone_code}})</option>
                    {% endfor %}
                  </select>
                </div>
                <div class="col-8">
                <input type="number" class="form-input" id="request-email"
                placeholder="{% trans "Phone number" %}" aria-label="Your Phone" name="phone_no">
                </div>
              </div>
            </div>

            <div class="form-group mb-4">
              <label for="request-comments" class="form-label"><b>{% trans "Message to doctor" %}</b></label>
              <textarea class="form-input" placeholder="{% trans "Type of treatment, desired destination" %}" name="comment" id="request-comments" cols="30" rows="5"></textarea>
            </div>

            <div class="pt-3">
              <div class="text-center">
                  <button type="submit" class="btn btn-primary" type="submit">{% trans "SEND MY INQUIRY" %}</button>
                </div>
            </div>
          </div>
        </form>
        </div>

        <div class="card-green mt-5 mt-md-0">
          <h5>{% trans "Find a Doctor" %}</h5>
          <form action="{% url 'clinics:clinics_search' %}" onsubmit="event.preventDefault(); goToSearch(document.getElementById('treatment_search').value)">


          <div class="form-box">

            <input type="text" class="form-input" id="treatment_search"
            placeholder="{% trans "Enter treatment, destinations, procedure" %}.." aria-label="Search">
            <p style="color: red; display: none;" id="search-error">{% trans "Please select from available options." %}</p>

          </div>

          <div class="pt-5">
            <div class="text-center">
                <button class="btn btn-primary" type="submit">{% trans "Search" %}</button>
              </div>
          </div>
        </form>
        </div>
      </div>
    </div>
  </div>
</div>

<script>
  function goToSearch(query) {
    let url;

    $.get(`/exists-in-treatments/?term=${query}&language={{language}}`,
      function(data) {
        if (data === "True") {
          $.post('/create-slug/', {
            slug: query
          }, function(data) {
           url = '{% url "clinics:clinics_search" %}' + '/' + data
      
          
          document.getElementById('search-error').style.display = 'none';
          window.location.href = url
          })

        } else {
          document.getElementById('search-error').style.display = 'block';
        }
      }
    );

  }
</script>
<script>
  $(document).ready(function(){ 
      $("#treatment_search").autocomplete({
          source: "/ajax_calls/search/?language={{language}}",
          open: function(){
              setTimeout(function () {
                  $('.ui-autocomplete').css('z-index', 99000);
              }, 0);
          }
        });
  });
</script>
{% endblock body %}