medicalSite/blog/urls.py
from django.urls import path
from . import views
app_name='blog'

urlpatterns=[
    path('',views.index, name='blog'),
    path('post/<str:slug>', views.blog_post, name="blog_post")
]

medicalSite/clinics/urls.py
from django.urls import path
from . import views
app_name='clinics'

urlpatterns=[
    path('add-clinic/',views.add_clinic, name="clinics_add_clinic"),
    path("clinic", views.search_clinic, name="clinics_search"),
    path('treatments/', views.treatments, name="clinic_treatments"),
    path("destinations", views.destinations, name="clinic_destinations"),
    path("destinations/<str:search_country>", views.destinations, name="clinic_destinations"),
    path("destinations/<str:search_country>/<str:search_city>", views.destinations, name="clinic_destinations"),

    path('free-quote/', views.get_free_quote, name= "free_quote_without_clinic"),
    path('<slug:clinic_slug>/', views.get_each_clinic, name= "clinics_each_detail"),
    path('<slug:clinic_slug>/add-review', views.get_reviews, name= "clinics_reviews"),
    path("clinic/<str:search_treatment>", views.search_clinic, name="clinics_search"),
    path("clinic/<str:search_treatment>/<str:search_country>", views.search_clinic, name="clinics_search"),
    path("clinic/<str:search_treatment>/<str:search_country>/<str:search_city>", views.search_clinic, name="clinics_search"),
    path("rankings/<str:category>", views.rankings, name="clinics_rankings"),
    path("rankings/<str:category>/<str:country>", views.rankings, name="clinics_rankings"),
    path("rankings/<str:category>/<str:country>/<str:city>", views.rankings, name="clinics_rankings"),
    path('run-interval', views.run_interval, name="run_interval"),
]

medicalSite/medicalSite/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from django.conf.urls.i18n import i18n_patterns

#local imports
from . import settings
from . import views


urlpatterns = [
    path('admin/', admin.site.urls),
    path('tinymce/', include('tinymce.urls')),
    path('i18n/', include('django.conf.urls.i18n')),
    path('change-currency/', views.change_currency, name= 'change_currency'),
    path('create-slug/', views.create_slug, name='create_slug'),
    path('exists-in-treatments/', views.exists_in_treatments, name='exists_in_treatments'),
    path('show-error', views.show_error, name='show_error'),
    path('set-in-session/', views.setInSession, name="set_in_session")
]

urlpatterns += i18n_patterns(
    path('', views.Home, name= 'home'),
    path('blog/', include("blog.urls"), name="blog"),
    path('contact/', views.Contact, name= 'contact'),
    path('about-us/', views.About, name= 'about'),
    path('sitemap/', views.Sitemap, name= 'sitemap'),
    path('terms-and-conditions/', views.TermsAndConditions, name= 'terms_and_conditions'),
    path('ajax_calls/search/', views.autocompleteModel),
    path('ajax_calls/country/search/', views.autocompleteCountryModel),
    path('', include("clinics.urls"), name="clinics"),
    prefix_default_language=False
)
handler404 = 'medicalSite.views.error_404'
handler500 = 'medicalSite.views.error_500'

if settings.DEBUG:
    urlpatterns+=static(settings.MEDIA_URL,document_root=settings.MEDIA_ROOT)

medicalSite/templates/main/about.html
{% extends 'main/base.html' %}

{% load static %}

{% load i18n %}





{% block title %}MyTripMed - {% trans "About Us" %}{% endblock title %}
{% block description %}{% trans "Compare in one click the most economical offers for your aesthetic treatment in the best clinics in the world." %}{% endblock description %}


{% block body %}



<section class="top-section pb-0">

  <div class="container heading-border">

    <h1 class="mb-3">{% trans "About Us" %}</h1>

  </div>

</section>



<div class="contact-top">

</div>



<div class="container mb-5 pb-5">

  <div class="row">

    <div class="col-md-12 container-border ">

      <div class="card card-sm">

        <p>

          {% trans "MyTripMed is the online comparator that allows you to book your treatment directly in the best clinics in the world. Our tool puts you in touch with doctors handpicked for their experience and quality of service.  Thus, we give you all the information you need to better compare the offers. You will therefore find the country of the practitioner, an overview of his professional career, his specialties and in particular his prices. We also provide you with before/after photos and real testimonials from other patients. This will allow you to choose more transparently. " %}

        </p><br><br>

        <p>

          {% trans "So, by booking your treatment on MyTripMed, you have the assurance of being treated by a renowned medical expert. In addition, you benefit from the most attractive offers on the market. Thanks to our portal, you can save up to 70% on the prices of dental care, hair transplant or cosmetic surgery. With MyTripMed, you benefit from the most optimal quality-price ratio." %}

        </p><br><br>

        <p>

          {% trans "Our expert advisors guarantee you full assistance in making a treatment appointment. They answer all your questions and make things easier for you. Likewise, they send you a free, non-binding quote on the type of operation you want to perform. This allows you to leave for your medical stay without surprises or hidden costs. In addition, we have selected for you the most famous destinations in the world for the quality of their services and their reduced rates: Turkey, Tunisia, Hungary, Romania, Mexico..." %}

        </p><br><br>

        <p>

          {% trans "In short, our mission is to give you access to a wide range of treatments. We help you get the look you dream of by letting you choose your own doctor. Also, we make sure you have a great medical trip without hurting your budget! " %}

        </p>


      </div>

    </div>



    

  </div>

</div>

</div>





{% endblock body %}

medicalSite/templates/main/contact.html
{% extends 'main/base.html' %}
{% load static %}
{% load i18n %}


{% block title %}MyTripMed - {% trans "Contact Us" %}{% endblock title %}
{% block description %}{% trans "Do not hesitate to contact us to ask your questions, give your suggestions and discover more about our services." %}{% endblock description %}  
{% block body %}

  <section class="top-section pb-0">
    <div class="container heading-border">
            <h1 class="mb-3">{% trans "Contact us at anytime!" %}</h1>
                <h5 class="text-dark">{% trans "Send us your suggestions or questions and let us know your expectations. We are happy to answer you as soon as possible." %}</h5>
              </div>
    </section>

    <div class="contact-top">
    </div>

  <div class="container mb-5 pb-5">   
    <div class="row">
      <div class="col-md-8 container-border container-border-left">
        <div class="form-left card card-sm">
          <form method="POST" action="" >
            {% csrf_token %}
          <h4 class="text-dark mb-4">{% trans "Now fill out the form below to get in touch with our customer service." %}</h4>
            <div class="row">
              <div class="col-md-4 mt-4">
                <label for="titleInput" class="form-label">{% trans "Title" %}*</label>
                <select class="form-select" id="titleInput" name="title">
                  <option value="" disabled selected>{% trans "Choose" %}</option>
                  <option value="Mr">Mr</option>
                  <option value="Mr">Mrs</option>
                  </select>
          </div>
              <div class="col-md-8 mt-4">
                <label for="nameInput" class="form-label">{% trans "Name" %}*</label>
              <input type="text" class="form-input"
            placeholder="{% trans "name" %}" aria-label="First Name" id="nameInput" name="name" required> 
          </div>
         
     

  <div class="col-md-12 mt-4">
    <label for="address1" class="form-label">{% trans "Address 1" %}*</label>
  <input type="text" class="form-input"
placeholder="{% trans "Enter your main address" %}" aria-label="Address 1" name="address1" id="address1" required>
</div>

<div class="col-md-12 mt-4">
  <label for="address2" class="form-label">{% trans "Address 2" %}</label>
<input type="text" class="form-input"
placeholder="{% trans "Enter your secondary address" %}" aria-label="Address 2" id="address2" name="address2">
</div>

<div class="col-md-3 mt-4">
  <label for="city" class="form-label">{% trans "City" %}*</label>
<input type="text" class="form-input"
placeholder="{% trans "City" %}" aria-label="City" id="city" name="city" required>
</div>
<div class="col-md-3 mt-4">
  <label for="State" class="form-label">{% trans "State" %}*</label>
<input type="text" class="form-input"
placeholder="{% trans "State" %}" aria-label="State" id="State" name="state" required>
</div>
<div class="col-md-3 mt-4">
  <label for="Country" class="form-label">{% trans "Country" %}*</label>

  <select class="form-select" id="Country" name="country" required>
    <option value="" selected disabled>{% trans "Country" %}</option>
    {% for country in all_countries %}
    <option value={{country.name}}>{{country.name}}</option>
    {% endfor %}
 </select>
</div>
<div class="col-md-3 mt-4">
  <label for="Zipcode" class="form-label">{% trans "Postal Code" %}*</label>
<input type="number" class="form-input"
placeholder="{% trans "Zipcode" %}" aria-label="Zipcode" id="Zipcode" name="zipcode" required>
</div>
        <div class="col-md-6 mt-4">
              <label for="email" class="form-label">{% trans "E-mail" %}*</label>
          <input type="email" class="form-input" placeholder="{% trans "Email" %}" aria-label="Email" id="email" name="email" required>
      </div>
   
        <div class="col-md-6 mt-4">
          <label for="code" class="form-label">{% trans "Phone Number" %}*</label>
              <input type="tel" class="form-input" 
              placeholder="{% trans "Phone number" %}" aria-label="Phone number" name="phone_number" required>
            
        </div>

        <div class="col-12 mt-4">
          <label for="message">{% trans "Message" %}*</label>
            <textarea class="form-input" 
            rows="4"
            placeholder="{% trans "Type your message" %}" id="message" required name="message"></textarea>
        </div>
      
            <div class="col-12 mt-5 pb-3">
                <div class="d-grid gap-2 d-md-flex justify-content-md-end">
              <button class="btn btn-primary" type="submit">{% trans "Send" %}</button>
            </div>
          </div>
        </div>

      </form>
    </div>      
    </div>

    <div class="col-md-4 container-border container-border-right">
        <a href="#" target="blank">
            <div class="card-green d-flex justify-content-between align-items-center mb-4">
                <div>
                    <h5 class="text-dark">{% trans "Call us" %}</h5>
                    <p class="p-big text-decoration-none"> 33 (0)9 74 33 82 33</p>
                        </div>
                    <img src="{% static 'img/call-icon.png' %}" alt="call-icon" class="contact-icon">        
                </div>
            </a>
        
            <a href="#" target="blank">
            <div class="card-green d-flex justify-content-between align-items-center mb-4">
                <div>
                    <h5 class="text-dark">{% trans "Chat on WhatsApp" %}</h5>
                    <p class="p-big text-decoration-none">45658-46565-51</p>
                </div>
                    <img src="{% static 'img/whatsapp-icon.png' %}" alt="call-icon" class="contact-icon">
                </div>
            </a>
           
            <a href="https://www.facebook.com/Mytripmed" target="blank">
                <div class="card-green d-flex justify-content-between align-items-center mb-4">
                    <div>
                        <h5 class="text-dark">{% trans "Like us on Facebook" %}</h5>
                        <p class="p-big text-decoration-none">{% trans "See what others are saying about us" %}</p>
                    </div>
                        <img src="{% static 'img/facebook-icon.png' %}" alt="call-icon" class="contact-icon">
                    </div>
                </a>
           
                <a href="#" target="blank">
                    <div class="card-green d-flex justify-content-between align-items-center mb-4">
                        <div>
                        <h5 class="text-dark">{% trans "Follow us on Twitter" %}</h5>
                        <p class="p-big text-decoration-none">{% trans "Or send us a tweet" %}</p>
                        </div>
                        <img src="{% static 'img/twitter-icon.png' %}" alt="call-icon" class="contact-icon">
                    </div>
                </a>
            </div>
        </div>
      </div>
    </div>


{% endblock body %}

medicalSite/templates/main/index.html
{% extends 'main/base.html' %}
{% load static %}
{% load i18n %}
{% load custom_tags %}

{% block title %}MyTripMed: {% trans "Treatment Abroad Price Comparison at Mytripmed" %}{% endblock title %} 
{% block description %}{% trans "MyTripMed: free comparator that helps you easily find doctors and clinics abroad at the best price." %}{% endblock description %}

{% block body %}

  <section class="top-section hero-section">
    <div class="container mt-md-1">
      <div class="row">
        <div class="col-md-5 hero-section-left">
          <h1>{% trans "Find World's Top Doctors" %}</h1>
          <div class="row">
            <div class="col-10">
              <p class="p-big">{% trans "Find the most attractive offers for the treatment you dream of and save up to 70% on prices." %}</p>
              <ul class="custom-list d-none d-md-block">
                <li>
                  <img src="{% static 'img/tick.png' %}" alt="list item">
                  <p>
                    {% trans "Qualified and renowned doctors." %}
                  </p>
                </li>
                <li>
                  <img src="{% static 'img/tick.png' %}" alt="list item">
                  <p>
                    {% trans "Personalized support." %}
                  </p>
                </li>
                <li>
                  <img src="{% static 'img/tick.png' %}" alt="list item">
                  <p>
                    {% trans "Free consultation and quotation." %}
                  </p>
                </li>
              </ul>
            </div>
          </div>


        </div>
        <div class="col-md-7">
          <img src="{% static 'img/top-section-image.jpg' %}" alt="#" class="d-none d-md-block">
        </div>
      </div>
      <div class="search-box">
        <div class="card" id="home-page-search" style="padding: 2.4rem 3.6rem !important;">
          {% comment %} <h5>
            {% trans "Find and book a Doctor's appointment" %}
          </h5> {% endcomment %}

          <form action="{% url 'clinics:clinics_search' %}" onsubmit="event.preventDefault(); goToSearch(document.getElementById('query').value, document.getElementById('country').value)">
            <input type="hidden" id="search" name="search" value="true">
          <div class="row mt-3">
            <div class="col-sm-9">
              <div class="form-group mb-4 mb-sm-0">
                <input type="text" class="form-input" id="query" name="query"
                  placeholder="{% trans "What treatment are you looking for?" %}" required>
                  
                <input type="text" class="form-input" id="country" style="margin-top: 10px;" name="country"
                placeholder="{% trans "Country" %}">
              </div>

            </div>
            <div class="col-sm-3 mt-3 d-flex justify-content-end align-items-end">
              <button type="submit" class="btn btn-secondary container-fluid">{% trans "Search" %}</button>
            </div>
            <p style="color: red; display: none;" id="search-error">{% trans "Please select from available options." %}</p>

          </div>
        </form>
        </div>
      </div>
    </div>

  </section>

  {% include 'main/popular-treatments.html' %}
  {% include 'main/popular-clinics.html' %}

  <section class="section-details">
    <div class="container">
      <h2 class="text-center">{% trans "Why rely on MyTripMed?" %}</h2>
      <div class="reasons-list">
        <div class="row">

          <div class="col-lg-4 col-sm-6 reason-box">
            <div class="row no-gutters">
              <div class="col-4">
                <img src="{% static 'img/logo-service.png' %}" alt="logo-service" class="logo-icon">
              </div>
              <div class="col-8 pb-4">
                <h4>{% trans "Economic offers" %}</h4>
                <p> {% trans "Save up to 70% on fares and take advantage of packages and promotional offers." %}</p>
              </div>
            </div>
          </div>

          <div class="col-lg-4 col-sm-6 reason-box">
            <div class="row no-gutters">
              <div class="col-4">
                <img src="{% static 'img/logo-clinic.png' %}" alt="logo-clinic" class="logo-icon">
              </div>
              <div class="col-8 pb-5">
                <h4>{% trans "Free Service" %}</h4>
                <p>{% trans "Take advantage of our free services to find the right doctor for your treatment. You pay on the spot without any hidden costs." %}</p>
              </div>
            </div>
          </div>

          <div class="col-lg-4 col-sm-6 reason-box">
            <div class="row no-gutters">
              <div class="col-4">
                <img src="{% static 'img/logo-checklist.png' %}" alt="logo-checklist" class="logo-icon">
              </div>
              <div class="col-8">
                <h4>{% trans "Patient support" %}</h4>
                <p>{% trans "Ask all your questions by phone or e-mail. Our experienced coordinators are there to support you in a personalized way." %}</p>
              </div>
            </div>
          </div>

          <div class="col-lg-4 col-sm-6 reason-box">
            <div class="row no-gutters">
              <div class="col-4">
                <img src="{% static 'img/logo-finance.png' %}" alt="logo-finance" class="logo-icon">
              </div>
              <div class="col-8">
                <h4>{% trans "Complete Information" %}</h4>
                <p>{% trans "Find all the useful data of doctors and clinics to make your selection easier: country, experience, specialties, guarantees, prices or packages, opinions and scores."%}
            </div>
          </div>
          </div>

          <div class="col-lg-4 col-sm-6 reason-box">
            <div class="row no-gutters">
              <div class="col-4">
                <img src="{% static 'img/logo-hotel.png' %}" alt="logo-hotel" class="logo-icon">
              </div>
              <div class="col-8">
                <h4>{% trans "Rigorous selection" %}</h4>
                <p>{% trans "We choose for you experienced and highly qualified doctors, but also internationally accredited clinics. " %}</p>
              </div>
            </div>
          </div>

          <div class="col-lg-4 col-sm-6 reason-box">
            <div class="row no-gutters">
              <div class="col-4">
                <img src="{% static 'img/logo-booking.png' %}" alt="logo-booking" class="logo-icon">
              </div>
              <div class="col-8">
                <h4>{% trans "Total satisfaction" %}</h4>
                <p>{% trans "You benefit from a personalized follow-up before and after the treatment to ensure your total satisfaction with our services." %}</p>
              </div>
            </div>
          </div>
        </div>
      </div>

    </div>
  </section>

  <section class="register">
    <div class="container">
      <div class="row">
        <div class="col-md-6">
          <h2>
            {% trans "How does it work ?" %}
          </h2>
          <p class="section-subheading">
            {% trans "It's very simple ! You will find detailed information on the clinics and treatments that interest you. You just have to compare prices and scores in order to choose the optimal offer for your medical stay." %}
          </p>
        </div>
      </div>

      <div class="row align-items-center">
        <div class="col-md-6">
          <img src="{% static 'img/logo-guidance.jpg' %}" class="steps-img" />
        </div>
        <div class="col-md-6">

          <div class="steps-wrapper">
            <div class="single-step">
              <h3 class="step-1">1</h3>
              <div class="content">
                <h4>{% trans "Choose your doctor" %}</h4>
                <p>{% trans "Select the best clinic and destination for your treatment." %}</p>
              </div>
            </div>

            <div class="single-step">
              <h3 class="step-1">2</h3>
              <div class="content">
                <h4>{% trans "Fill out the contact form" %}</h4>
                <p>{% trans "Add your contact details and indicate the date of your appointment." %}</p>
              </div>
            </div>

            <div class="single-step">
              <h3 class="step-1">3</h3>
              <div class="content">
                <h4>{% trans "Perform your treatment" %}</h4>
                <p>{% trans "Book your flight and enjoy a discounted medical stay with no hidden costs." %}</p>
              </div>
            </div>
          </div>
          <div class="steps-bg">
          </div>
        </div>
      </div>
    </div>
    </div>
  </section>
<script>
  function slugify_query(query) {
    $.post('/create-slug/', {
      slug: query
    }, function(data) {

    })
  }
  async function goToSearch(query, country) {
    let url;

    $.get(`/exists-in-treatments/?term=${query}&country=${country}&language={{language}}`,
      function(data) {
        if (data === "True") {
          $.post('/create-slug/', {
            slug: query
          }, function(data) {
            if (country) {
           url = '{% url "clinics:clinics_search" %}' + '/' + data + '/' + country
          } else {
           url = '{% url "clinics:clinics_search" %}' + '/' + data
      
          }
          document.getElementById('search-error').style.display = 'none';
          window.location.href = url
          })

        } else {
          document.getElementById('search-error').style.display = 'block';
        }
      }
    );


    

  }
</script>
<script>
  $(document).ready(function(){ 
      $("#query").autocomplete({
          source: "/ajax_calls/search/?language={{language}}",
          open: function(){
              setTimeout(function () {
                  $('.ui-autocomplete').css('z-index', 99000);
              }, 0);
          }
        });
  });

  $(document).ready(function(){ 
      $("#country").autocomplete({
          source: "/ajax_calls/country/search/?language={{language}}",
          open: function(){
              setTimeout(function () {
                  $('.ui-autocomplete').css('z-index', 99000);
              }, 0);
          }
        });
  });
</script>
{% endblock body %}

medicalSite/templates/main/popular-clinics.html
{% load i18n %}

<section class="destination-section">
    <div class="container">
        <h2>
           {% trans "Our best destinations" %}
        </h2>
        <div class="destination-list">
            {% for i in countries %}
                <div class="destination-card">
                    <div class="destination-card-overlay"></div>
                            {% if i.country.img %}
                            <img
                            src="{{ i.country.img.url }}"
                            alt="#" class="destination-card-image">
                            {% endif %}

                    <div class="destination-card-content">
                        <h4 class="destination-card-title">
                            {{i}}
                        </h4>
                        <div class="text-right">
                            {% comment %} <a href="/clinic/search?country={{country}}&query=" class="btn btn-sm btn-outline-white"> {% endcomment %}
                            <a href="{% url 'clinics:clinic_destinations' %}?country={{i}}" class="btn btn-sm btn-outline-white">
                                {% trans "See Clinics" %}
                            </a>
                        </div>
                    </div>
                </div>
            {% endfor %}
        </div>
  
        {% comment %} <div class="text-center">
        <a href="#" class="btn btn-primary">
            View all Destinations
        </a>
        </div> {% endcomment %}
  
    </div>
</section>

medicalSite/templates/main/popular-treatments.html
{% load static %}
{% load i18n %}

<section class="treatment-section bg-cream">
    <div class="container">
      <h2>
        {% trans "Our most popular treatments" %}
      </h2>
      <p class="section-subheading">
        {% trans "Choose from a wide range of aesthetic, dental and hair treatments." %}
      </p>

      <div class="treatment-list my-5">
        <div class="row">
          {% for treatment in popular_treatments %}
          <div class="col-lg-4 col-md-6">
            <div class="treatment-card">
              <div class="treatment-card-image">
                {% if treatment.img %}
                <img src="{{ treatment.img.url }}" alt="#">
                {% endif %}
              </div>
              <div class="treatment-card-content">
                <div>
                  <h5 class="text-dark mb-2">
                    {{ treatment.headline }}
                  </h5>

                  <ul class="treatment-card-list">
                    {% for i in treatment.allpopularnames.all %}
                    <li>
                       <a class="p-sm text-grey" href="{% url "clinics:clinics_search" %}/{{ i.treatment_name.slug }}">{{ i.treatment_name }}</a> 
                    </li>
                    {% endfor %}

                  </ul>
                 
                </div>
              </div>
            </div>
          </div>
          {% endfor %}
        </div>
      </div>
    </div>
  </section>