medicalSite/blog/urls.py
from django.urls import path
from . import views
app_name='blog'

urlpatterns=[
    path('',views.index, name='blog'),
    path('post/<str:slug>', views.blog_post, name="blog_post")
]

medicalSite/clinics/urls.py
from django.urls import path
from . import views
app_name='clinics'

urlpatterns=[
    path('add-clinic/',views.add_clinic, name="clinics_add_clinic"),
    path("clinic", views.search_clinic, name="clinics_search"),
    path('treatments/', views.treatments, name="clinic_treatments"),
    path("destinations", views.destinations, name="clinic_destinations"),
    path("destinations/<str:search_country>", views.destinations, name="clinic_destinations"),
    path("destinations/<str:search_country>/<str:search_city>", views.destinations, name="clinic_destinations"),

    path('free-quote/', views.get_free_quote, name= "free_quote_without_clinic"),
    path('<slug:clinic_slug>/', views.get_each_clinic, name= "clinics_each_detail"),
    path('<slug:clinic_slug>/add-review', views.get_reviews, name= "clinics_reviews"),
    path("clinic/<str:search_treatment>", views.search_clinic, name="clinics_search"),
    path("clinic/<str:search_treatment>/<str:search_country>", views.search_clinic, name="clinics_search"),
    path("clinic/<str:search_treatment>/<str:search_country>/<str:search_city>", views.search_clinic, name="clinics_search"),
    path("rankings/<str:category>", views.rankings, name="clinics_rankings"),
    path("rankings/<str:category>/<str:country>", views.rankings, name="clinics_rankings"),
    path("rankings/<str:category>/<str:country>/<str:city>", views.rankings, name="clinics_rankings"),
    path('run-interval', views.run_interval, name="run_interval"),
]

medicalSite/medicalSite/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from django.conf.urls.i18n import i18n_patterns

#local imports
from . import settings
from . import views


urlpatterns = [
    path('admin/', admin.site.urls),
    path('tinymce/', include('tinymce.urls')),
    path('i18n/', include('django.conf.urls.i18n')),
    path('change-currency/', views.change_currency, name= 'change_currency'),
    path('create-slug/', views.create_slug, name='create_slug'),
    path('exists-in-treatments/', views.exists_in_treatments, name='exists_in_treatments'),
    path('show-error', views.show_error, name='show_error'),
    path('set-in-session/', views.setInSession, name="set_in_session")
]

urlpatterns += i18n_patterns(
    path('', views.Home, name= 'home'),
    path('blog/', include("blog.urls"), name="blog"),
    path('contact/', views.Contact, name= 'contact'),
    path('about-us/', views.About, name= 'about'),
    path('sitemap/', views.Sitemap, name= 'sitemap'),
    path('terms-and-conditions/', views.TermsAndConditions, name= 'terms_and_conditions'),
    path('ajax_calls/search/', views.autocompleteModel),
    path('ajax_calls/country/search/', views.autocompleteCountryModel),
    path('', include("clinics.urls"), name="clinics"),
    prefix_default_language=False
)
handler404 = 'medicalSite.views.error_404'
handler500 = 'medicalSite.views.error_500'

if settings.DEBUG:
    urlpatterns+=static(settings.MEDIA_URL,document_root=settings.MEDIA_ROOT)

medicalSite/templates/ranking/index 2.html
{% extends 'main/base.html' %} {% load static %}
{% load i18n %}
{% load mathfilters %}
{% load custom_tags %}


{% block title %}{% if not country %}{% trans "Top ranking clinics for" %} {{ category }}{% elif not city and country %}{% trans "Top ranking clinics for" %} {{ category }} {% trans "on" %} {{ country }}{% else %}{% trans "Top ranking clinics for" %} {{ category }} {% trans "at" %} {{ city }} {% trans "on" %} {{ country }}{% endif %}{% endblock title %}
{% block description %}{% if not country %}{% trans "Top ranking clinics for" %} {{ category }}{% elif not city and country %}{% trans "Top ranking clinics for" %} {{ category }} {% trans "on" %} {{ country }}{% else %}{% trans "Top ranking clinics for" %} {{ category }} {% trans "at" %} {{ city }} {% trans "on" %} {{ country }}{% endif %}{% endblock description %}


{% block body %}

<section class="results-section top-section">
    <div class="container">
        <h2 class="text-dark mb-5 text-center pb-2">
            {% trans "Ranking of top" %} {% if category == "hair-transplant" %}{% trans "Hair Transplant" %}{% else %}{{ category | capfirst }}{% endif %} {% trans "clinics and doctors" %} {% if not city and country %}{% trans "on" %} {{ country }}{% elif city and country %}{% trans "at" %} {{city}} {% trans "on" %} {{country}}{% endif %}
        </h2>

        <div class="card">
            <div class="card-body">
                <div class="table-top fs-4">

                    <a href="{% url 'clinics:clinics_rankings' 'dentals' %}" type="button" class="btn btn{% if category == "dentals" %}-top{% else %}-bottom{% endif %} fs-2 text-600 {% if category == "dentals" %}active{% endif %}">
                        <i class="thead{% if category == "dentals" %}-icon{% endif %}" data-feather="smile"></i>
                        {% trans "Dentals" %}</a>

                    <a href="{% url 'clinics:clinics_rankings' 'aesthetic' %}" type="button" class="btn btn{% if category == "aesthetic" %}-top{% else %}-bottom{% endif %} fs-2 text-600 {% if category == "aesthetic" %}active{% endif %}">
                        <i class="thead{% if category == "aesthetic" %}-icon{% endif %}" data-feather="heart"></i>
                        {% trans "Aesthetic" %}</a>

                    <a href="{% url 'clinics:clinics_rankings' 'hair-transplant' %}" type="button" class="btn btn{% if category == "hair-transplant" %}-top{% else %}-bottom{% endif %} fs-2 text-600 {% if category == "hair-transplant" %}active{% endif %}">
                        <i class="thead{% if category == "hair-transplant" %}-icon{% endif %}" data-feather="globe"></i>
                        {% trans "Hair Transplant" %}</a>

                </div>

                <div class="table-bottom fs-4">
                    {% if not country %}
                        {% for i in filter_destinations %}
                        <a type="button" class="btn btn-2 fs-4 text-400" href="{% url 'clinics:clinics_rankings' category i.country %}">
                            {{ i.country }}
                            <img src="https://flagicons.lipis.dev/flags/4x3/{{ i.country_flag }}.svg" alt="" class="flag">
                        </a>
                        {% endfor %}
                    {% else %}
                        {% for i in filter_destinations %}
                        <a type="button" class="btn btn-2 fs-4 text-400" href="{% url 'clinics:clinics_rankings' category country i %}">
                            {{ i }}
                        </a>
                        {% endfor %}
                    {% endif %}
                </div>

                <table class="table table fs-3 mt-sm-4 text-center">
                    <thead>
                        <tr>
                            <th class="text-purple text-600" scope="col">{% trans "Rank" %}
                                <a class="text-purple text-600" href=""><i class="thead-icon" data-feather="chevron-up"></i></a>
                            </th>
                            <th scope="col">{% trans "Doctors & Clinic" %}
                            </th>
                            <th scope="col">{% trans "Regions" %}
                            </th>
                            <th scope="col">{% trans "Reviews scores" %}
                                <i class="thead-icon" data-feather="chevron-down"></i>
                            </th>
                            <th scope="col">{% trans "Quality scores" %}
                                <i class="thead-icon" data-feather="chevron-down"></i>
                            </th>
                            <th class="text-purple text-600" scope="col">{% trans "Points" %}
                                <i class="thead-icon" data-feather="chevron-down"></i>
                            </th>
                        </tr>
                    </thead>
                    <tbody>
                        {% for clinic in ranking_clinics %}
                        <tr>
                            <th class="text-purple text-800" scope="row mt-5 mb-4">{{ clinic.rank }}
                                {% if clinic.old_rank %}
                                {% if clinic.old_rank > clinic.rank %}

                                <span class="text-success"><i data-feather="chevron-up"></i>
                                    <sup>{{ clinic.old_rank|sub:clinic.rank }}</sup>
                                </span>
                                {% else %}
                                <span class="text-danger"><i data-feather="chevron-down"></i>
                                    <sub>{{ clinic.rank|sub:clinic.old_rank }}</sub>
                                </span>
                                {% endif %}
                                {% endif %}

                            </th>
                            <td>
                                {% if clinic.clinic_available %}
                                <a href="{% url 'clinics:clinics_each_detail' clinic.slug %}" target="_blank" class="text-purple text-600">

                                    {% if clinic.logo %}

                                    <img src="{{ clinic.logo.url }}" alt="" class="company">
                                </td>
                                {% else %}
                                {{ clinic.name }}
                                {% endif %}
                                
                            </a>
                            {% else %}
                            {% if clinic.logo %}
                            <img src="{{ clinic.logo.url }}" alt="" class="company">
                            {% else %}
                            <span class="text-400">
                                {{ clinic.name }}
                            </span>
                            {% endif %}
                            {% endif %}
                        </td>

                            <td>
                                {% if clinic.country_flag %}
                                <img src="https://flagicons.lipis.dev/flags/4x3/{{ clinic.country_flag }}.svg" alt="" class="region">
                                {% endif %}
                                {{ clinic.table_country_name }}
                            </td>
                            <td>{{ clinic.feedback_score }}</td>
                            <td>{{ clinic.quality_score }}</td>
                            <td class="text-purple text-800">{{ clinic.final_score }}</td>
                        </tr>
                        {% endfor %}
                    </tbody>
                </table>

            </div>
        </div>
    </div>

    <div class="d-grid gap-1 col-sm-2 mx-sm-auto pt-5">
        {% if next_page_exist %}
        <a href="?page={{next_page}}" class="btn btn-primary" type="button">{% trans "Show More" %}</a>
        {% endif %}
    </div>

</section>


{% endblock body %}

medicalSite/templates/ranking/index.html
{% extends 'main/base.html' %} {% load static %}
{% load i18n %}
{% load mathfilters %}
{% load custom_tags %}


{% block title %}{% if not country %}{% trans "The top 20" %} {% if category == "hair-transplant" %}{% trans "hair transplant clinics" %}{% elif category == "dentals" %}{% trans "dentists" %}{% elif category == "aesthetic" %}{% trans "aesthetic surgery specialists" %}{% endif %} {% trans "abroad - Mytripmed" %} {% elif not city and country %}{% trans "The top 20" %} {% if category == "hair-transplant" %}{% trans "hair transplant clinics" %}{% elif category == "dentals" %}{% trans "dentists" %}{% elif category == "aesthetic" %}{% trans "aesthetic surgery specialists" %}{% endif %} {% trans "in" %} {{ country }}{% else %}{% trans "The top 20" %} {% if category == "hair-transplant" %}{% trans "hair transplant clinics" %}{% elif category == "dentals" %}{% trans "dentists" %}{% elif category == "aesthetic" %}{% trans "aesthetic surgery specialists" %}{% endif %} {% trans "at" %} {{ city }} {% trans "in" %} {{ country }}{% endif %}{% endblock title %}
{% block description %}{% if not country %}{% trans "List of the best" %} {% if category == "hair-transplant" %}{% trans "hair transplant clinics" %}{% elif category == "dentals" %}{% trans "dentists" %}{% elif category == "aesthetic" %}{% trans "aesthetic surgeons" %}{% endif %} {% trans "classified by customer reviews and quality of services" %} {% elif not city and country %}{% trans "List of the best" %} {% if category == "hair-transplant" %}{% trans "hair transplant clinics" %}{% elif category == "dentals" %}{% trans "dentists" %}{% elif category == "aesthetic" %}{% trans "aesthetic surgeons" %}{% endif %} {% trans "classified by customer reviews and quality of services" %} {% trans "in" %} {{ country }}{% else %}{% trans "List of the best" %} {% if category == "hair-transplant" %}{% trans "hair transplant clinics" %}{% elif category == "dentals" %}{% trans "dentists" %}{% elif category == "aesthetic" %}{% trans "aesthetic surgeons" %}{% endif %} {% trans "classified by customer reviews and quality of services" %} {% trans "at" %} {{ city }} {% trans "in" %} {{ country }}{% endif %}{% endblock description %}


{% block body %}    

<section class="dental-clinic-section top-section">
    <div class="container">
      <h1 class="text-dark mb-5 text-center pb-2">
        {% trans "Ranking of top" %} {% if category == "hair-transplant" %}{% trans "hair transplant specialists" %}{% elif category == "dentals" %}{% trans "dentists" %}{% elif category == "aesthetic" %}{% trans "aesthetic surgery specialists" %}{% endif %} {% if not city and country %}{% trans "in" %} {{ country }}{% elif city and country %}{% trans "at" %} {{city}} {% trans "in" %} {{country}}{% endif %}
      </h1>

      <div class="card p-0">
        <div class="card-header bg-white">
          <div class="filters-categories">

            <div class="category-filter" onclick="window.location='{% url 'clinics:clinics_rankings' 'dentals' %}';">
              <a href="{% url 'clinics:clinics_rankings' 'dentals' %}" style="display: hidden;"></a>
              <input class="category-input" type="radio" name="category" id="category-1"  style="cursor: pointer !important;" {% if category == "dentals" %}checked{% endif %}>
              <label class="category-label" for="category-1"  style="cursor: pointer !important;">
                <img src="{% static 'img/tooth.png' %}" alt="tooth" class="type-icon">
                {% trans "Dentals" %}
              </label>
            </div>

            <div class="category-filter" onclick="window.location='{% url 'clinics:clinics_rankings' 'aesthetic' %}';">
              <a href="{% url 'clinics:clinics_rankings' 'aesthetic' %}" style="display: hidden;"></a>
              <input class="category-input" type="radio" name="category" id="category-2"  style="cursor: pointer !important;" {% if category == "aesthetic" %}checked{% endif %}>
              <label class="category-label" for="category-2"  style="cursor: pointer !important;">
                <img src="{% static 'img/Aesthetic.png' %}" alt="tooth" class="type-icon">
                {% trans "Aesthetic" %}
              </label>
            </div>

            <div class="category-filter" onclick="window.location='{% url 'clinics:clinics_rankings' 'hair-transplant' %}';">
              <a href="{% url 'clinics:clinics_rankings' 'hair-transplant' %}" style="display: hidden;"></a>
              <input class="category-input" type="radio" name="category" id="category-3"  style="cursor: pointer !important;" {% if category == "hair-transplant" %}checked{% endif %}>
              <label class="category-label" for="category-3"  style="cursor: pointer !important;">
                <img src="{% static 'img/hair.png' %}" alt="tooth" class="type-icon">
                {% trans "Hair Transplant" %}
              </label>
            </div>


          </div>

          <div class="filters-countries">

            {% if not country %}
                        {% for i in filter_destinations %}
                        <a href="{% url 'clinics:clinics_rankings' category i.country %}" style="display: hidden;"></a>
                        <div class="flag-filter" onclick="window.location='{% url 'clinics:clinics_rankings' category i.country %}';">
                            <input type="radio" hidden name="country" id="{{ i.country }}" class="radio-btn" style="cursor: pointer !important;" {% if i.country == country %}checked{% endif %}>
                            <label for="{{ i.country }}" style="cursor: pointer !important;">
                              {{ i.country }}<img src="https://flagicons.lipis.dev/flags/4x3/{{ i.country_flag }}.svg" alt="{{ i.country }}" class="flag">
                            </label>
                          </div>
                        {% endfor %}
                    {% else %}
                        {% for i in filter_destinations %}
                        <a href="{% url 'clinics:clinics_rankings' category country i %}" style="display: hidden;"></a>
                        <div class="flag-filter" onclick="window.location='{% url 'clinics:clinics_rankings' category country i %}';">
                            <input type="radio" hidden name="city" id="{{ i }}" class="radio-btn" style="cursor: pointer !important;" {% if i == city %}checked{% endif %}>
                            <label for="{{ i }}" style="cursor: pointer !important;">
                              {{ i }}
                            </label>
                          </div>
                        {% endfor %}
                    {% endif %}
          </div>

        </div>


        <div class="card-body">
          <table class="table table-sm fs-3 text-center text-400 pt-0 mt-0">
            <thead>
              <tr>
                <th class="text-purple text-400 first-col" scope="col" style="min-width: 11rem">{% trans "Rank" %}
                  <i class="thead-icon" data-feather="chevron-up"></i>
                </th>
                <th scope="col" style="min-width: 20rem;" id="doctors_and_clinic_logo">{% trans "Doctors & Clinic" %}
                </th>
                <th scope="col" style="min-width: 15rem;">{% trans "Regions" %}
                </th>
                <th scope="col" style="min-width: 20rem;">{% trans "Review score" %}
                  <i class="thead-icon" data-feather="chevron-down"></i>
                  <i class="info-icon" data-feather="info"></i>

                  <div class="info-dialog">
                    {% trans "<b>The average score of reviews</b> on Google and other platforms recalculate to get more accurate value." %}
                  </div>
                </th>
                <th scope="col" style="min-width: 20rem;">{% trans "Quality score" %}
                  <i class="thead-icon" data-feather="chevron-down"></i>
                   <i class="info-icon" data-feather="info"></i>
                   <div class="info-dialog">
                    {% trans "<b>Quality score:</b> refers to the quality of the services offered and the transparency of the clinic. In order to calculate the score, different factors are collected such as: accreditations, certifications, price transparency, expertise in the domain, years of experience, quality of the clinic, languages spoken, etc." %}
                  </div>
                </th>
                <th class="text-purple text-400 last-col" scope="col" style="min-width: 15rem;">{% trans "Points" %}
                  <i class="thead-icon" data-feather="chevron-down"></i>
                  <i class="info-icon" data-feather="info"></i>
                  <div class="info-dialog">
                    {% trans "The sum of reviews score plus quality score." %}
                  </div>
                </th>
              </tr>
            </thead>
            <tbody>
                {% for clinic in ranking_clinics %}

              <tr>
                <th class="text-purple text-600 first-col" scope="row mt-5 mb-4">{{ clinic.rank }}
                  <span class="text-purple text-700 ranking">
                    {% if clinic.old_rank %}
                                {% if clinic.old_rank > clinic.rank %}

                                <span class="text-success"><i style="font-family: 'FontAwesome' !important;" class="fa fa-sort-asc" aria-hidden="true"></i>
                                    <sup>{{ clinic.old_rank|sub:clinic.rank }}</sup>
                                </span>
                                {% elif clinic.old_rank < clinic.rank  %}
                                <span class="text-danger"><i style="font-family: 'FontAwesome' !important;" class="fa fa-sort-desc" aria-hidden="true"></i>
                                    <sub>{{ clinic.rank|sub:clinic.old_rank }}</sub>
                                </span>
                                {% else %}
                                <i class="pointer" data-feather="minus"></i></span>
                                {% endif %}
                                {% endif %}
                </th>
                <td class="company-logo">
                    {% if clinic.clinic_available %}
                                <a href="{% url 'clinics:clinics_each_detail' clinic.slug %}" target="_blank" class="text-purple text-600">

                                    {% if clinic.logo %}

                                    <img src="{{ clinic.logo.url }}" alt="{{ clinic.name }}" class="company">
                                {% else %}
                                {{ clinic.name }}
                                {% endif %}
                                
                            </a>
                            {% else %}
                            {% if clinic.logo %}
                            <img src="{{ clinic.logo.url }}" alt="{{ clinic.name }}" class="company">
                            {% else %}
                            <span class="text-400">
                                {{ clinic.name }}
                            </span>
                            {% endif %}
                            {% endif %}
                </td>
                <td class="region-text">
                    {% if clinic.country_flag %}
                    <img src="https://flagicons.lipis.dev/flags/4x3/{{ clinic.country_flag }}.svg" alt="" class="region">
                    {% endif %}
                    {{ clinic.table_country_name }}
                </td>
                <td>{{ clinic.feedback_score }}</td>
                <td>{{ clinic.quality_score }}</td>
                <td class="text-purple text-700 last-col">{{ clinic.final_score }}</td>
              </tr>
              {% endfor %}
            </tbody>
          </table>

        </div>
      </div>


      <div class="d-grid gap-1 col-sm-2 mx-sm-auto pt-5">
        {% if next_page_exist %}
        <!-- <a href="?page={{next_page}}" class="btn btn-primary" type="button">{% trans "Show More" %}</a> -->
        <button class="btn btn-primary" type="button" onclick="nextPage()">{% trans "Show More" %}</button>
        {% endif %}
      </div>
    </div>

    

  </section>
<script>
  function nextPage() {
    const url = window.location.pathname + "?page={{next_page}}";
    // window.history.pushState({}, '', url);
    $("#doc").load(url);
  }
</script>
  {% endblock body %}