medicalSite/blog/urls.py
from django.urls import path
from . import views
app_name='blog'

urlpatterns=[
    path('',views.index, name='blog'),
    path('post/<str:slug>', views.blog_post, name="blog_post")
]

medicalSite/clinics/urls.py
from django.urls import path
from . import views
app_name='clinics'

urlpatterns=[
    path('add-clinic/',views.add_clinic, name="clinics_add_clinic"),
    path("clinic", views.search_clinic, name="clinics_search"),
    path('treatments/', views.treatments, name="clinic_treatments"),
    path("destinations", views.destinations, name="clinic_destinations"),
    path("destinations/<str:search_country>", views.destinations, name="clinic_destinations"),
    path("destinations/<str:search_country>/<str:search_city>", views.destinations, name="clinic_destinations"),

    path('free-quote/', views.get_free_quote, name= "free_quote_without_clinic"),
    path('<slug:clinic_slug>/', views.get_each_clinic, name= "clinics_each_detail"),
    path('<slug:clinic_slug>/add-review', views.get_reviews, name= "clinics_reviews"),
    path("clinic/<str:search_treatment>", views.search_clinic, name="clinics_search"),
    path("clinic/<str:search_treatment>/<str:search_country>", views.search_clinic, name="clinics_search"),
    path("clinic/<str:search_treatment>/<str:search_country>/<str:search_city>", views.search_clinic, name="clinics_search"),
    path("rankings/<str:category>", views.rankings, name="clinics_rankings"),
    path("rankings/<str:category>/<str:country>", views.rankings, name="clinics_rankings"),
    path("rankings/<str:category>/<str:country>/<str:city>", views.rankings, name="clinics_rankings"),
    path('run-interval', views.run_interval, name="run_interval"),
]

medicalSite/medicalSite/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from django.conf.urls.i18n import i18n_patterns

#local imports
from . import settings
from . import views


urlpatterns = [
    path('admin/', admin.site.urls),
    path('tinymce/', include('tinymce.urls')),
    path('i18n/', include('django.conf.urls.i18n')),
    path('change-currency/', views.change_currency, name= 'change_currency'),
    path('create-slug/', views.create_slug, name='create_slug'),
    path('exists-in-treatments/', views.exists_in_treatments, name='exists_in_treatments'),
    path('show-error', views.show_error, name='show_error'),
    path('set-in-session/', views.setInSession, name="set_in_session")
]

urlpatterns += i18n_patterns(
    path('', views.Home, name= 'home'),
    path('blog/', include("blog.urls"), name="blog"),
    path('contact/', views.Contact, name= 'contact'),
    path('about-us/', views.About, name= 'about'),
    path('sitemap/', views.Sitemap, name= 'sitemap'),
    path('terms-and-conditions/', views.TermsAndConditions, name= 'terms_and_conditions'),
    path('ajax_calls/search/', views.autocompleteModel),
    path('ajax_calls/country/search/', views.autocompleteCountryModel),
    path('', include("clinics.urls"), name="clinics"),
    prefix_default_language=False
)
handler404 = 'medicalSite.views.error_404'
handler500 = 'medicalSite.views.error_500'

if settings.DEBUG:
    urlpatterns+=static(settings.MEDIA_URL,document_root=settings.MEDIA_ROOT)

medicalSite/treatment/models.py
from django.utils.text import slugify
from django.db import models
from clinics.models import Clinic, Currency, Language, ClinicReviews

class ClinicReviewsProxy(ClinicReviews):
    class Meta:
        proxy = True
        verbose_name_plural='Clinic Reviews'
        verbose_name='Clinic Reviews'

# Create your models here.
class Treatment(models.Model):
    clinic = models.ForeignKey(Clinic,on_delete=models.CASCADE,related_name='alltreatments', null=True)
    slug = models.SlugField(null= True, blank= True)
    language = models.ForeignKey(Language, on_delete=models.CASCADE, related_name='treatmentlanguage', blank= True, null=True)
    searched_treatment = models.CharField(max_length= 256, blank= False, null= False)
    price = models.FloatField(blank= False, null= False)
    price_type = models.CharField(max_length= 256, blank= True, null= True)
    package_info_1 = models.CharField(max_length= 556, blank= True, null= True)
    package_info_2 = models.CharField(max_length= 556, blank= True, null= True)
    package_info_3 = models.CharField(max_length= 556, blank= True, null= True)
    package_info_4 = models.CharField(max_length= 556, blank= True, null= True)
    currency=models.ForeignKey(Currency,on_delete=models.CASCADE,related_name='currency',blank=True,null=True)
    created= models.DateTimeField(auto_now=True)
    status = models.BooleanField(default= True)

    class Meta:
        # unique_together = ('clinic', 'searched_treatment', 'language')
        ordering=('-created',)
        verbose_name_plural='Treatments'

    def __str__(self):
        return self.searched_treatment

    def save(self, *args, **kwargs):
        slug = self.searched_treatment
        self.slug = slugify(slug, allow_unicode=True)
        super(Treatment, self).save(*args, **kwargs)




# proxy models



from clinics.models import ClinicTreatmentLeads, Contact, ClinicAdd
from blog.models import BlogContact

class ClinicTreatmentLeadsProxy(ClinicTreatmentLeads):
    class Meta:
        proxy = True
        verbose_name_plural='Clinic Treatment Leads'
        verbose_name='Clinic Treatment Leads'
    
class ContactProxy(Contact):
    class Meta:
        proxy = True
        verbose_name_plural='Contacts'
        verbose_name='Contacts'

class ClinicAddProxy(ClinicAdd):
    class Meta:
        proxy = True
        verbose_name_plural='Clinic Add'
        verbose_name='Clinic Add'

class BlogContactProxy(BlogContact):
    class Meta:
        proxy = True
        verbose_name_plural='Blog Contact'
        verbose_name='Blog Contact'

medicalSite/clinics/views.py
from django.shortcuts import redirect, render
from django.http import HttpResponse

from treatment.models import Treatment
from .models import *
from django.db.models import Q
import json
from operator import attrgetter
import sys
from django.contrib import messages
from urllib.parse import unquote

import json

from google_currency import CODES

import pycountry
import threading
import time
from .codes import CODES

from forex_python.converter import CurrencyRates
 

one_usd_to_aed = 3.67

CODES = {
    "GBP": "Pound sterling",
    "AUD": "Australian Dollar",
    "EUR": "Euro",
    "CAD": "Canadian Dollar",
    "CHF": "Swiss Franc",
    "AED": "United Arab Emirates Dirham",
    "USD": "United States Dollar",
}

def thread_function():
    c = CurrencyRates()
    while True:
        # run for loop on CODES 
        # delete all the records from the table

        CurrencyPricesList = list()

        # get the latest prices from the API and save it to the database
        for code in list(CODES.keys()):
            # amount = float(json.loads(convert(code, 'USD', 1))['amount'])
            try:
                if code == 'AED':
                    amount = 1/one_usd_to_aed
                elif code == 'USD':
                    amount = 1
                else:
                    amount = float(c.convert(code, 'USD', 1))
            except Exception:
                continue
            print(code, amount)
            # CurrencyPrices.objects.create(code=code, price=amount)
            CurrencyPricesList.append(CurrencyPrices(code=code, price=amount))

        CurrencyPrices.objects.all().delete()
        CurrencyPrices.objects.bulk_create(CurrencyPricesList)
        # sleep for 12 hrs
        time.sleep(43200)


def run_interval():
    t = threading.Thread(target=thread_function)
    t.start()
    return HttpResponse("Hello, world. You're at the run_interval.")

def get_each_clinic(request, clinic_slug):
    random_treatments = []
    clinic_data = Clinic.objects.get(slug=clinic_slug, language=Language.objects.get(code=request.LANGUAGE_CODE), status= 'publish')
    clinic_images = json.dumps(
        [{"src": i.image.url, "subHtml": ""} for i in clinic_data.allimages.all()])
    cover_image = clinic_data.allimages.filter().first()


    treatments = clinic_data.alltreatments.filter(language__code=request.LANGUAGE_CODE).all()
    # get first 2 treatments
    for treatment in treatments:
        random_treatments.append(treatment)
        if len(random_treatments) == 2:
            break

    # join treatments
    two_random_treatments = ', '.join(map(str, random_treatments))

    # clinic packages
    clinic_packages = clinic_data.allpackagesforclinic.filter(language__code=request.LANGUAGE_CODE).all()
    return render(request, "clinic/clinic-page.html", {"cover_image": cover_image, "clinic_data": clinic_data, "clinic_images": clinic_images, "two_random_treatments": two_random_treatments, "clinic_packages": clinic_packages})


def get_reviews(request, clinic_slug):
    clinic_data = Clinic.objects.get(slug=clinic_slug, language=Language.objects.get(code=request.LANGUAGE_CODE), status= 'publish')
    all_countries = Country.objects.filter(language=Language.objects.get(code=request.LANGUAGE_CODE)).reverse()

    if request.method == 'POST':
        name = request.POST.get("name")
        email = request.POST.get("email")
        review = request.POST.get("review")

        quality_rating = request.POST.get('QualityStar')
        service_rating = request.POST.get('ServiceStar')
        cleanliness_rating = request.POST.get('CleanlinessStar')
        comfort_rating = request.POST.get('ComfortStar')
        communication_rating = request.POST.get('CommunicationStar')


        review_instance= ClinicReviews.objects.create(clinic=clinic_data, name=name, email=email, review=review,
        quality_rating=quality_rating, service_rating=service_rating, cleanliness_rating=cleanliness_rating, comfort_rating=comfort_rating, communication_rating=communication_rating)
        review_instance.save()
        if request.LANGUAGE_CODE == 'fr':
            messages.success(request, 'Votre avis a été envoyé avec succès.')
        else:
            messages.success(request, 'Your review has been submitted successfully.')
        return redirect(f'/{clinic_slug}')

    context = {
        "clinic_data": clinic_data, 
        "all_countries": all_countries
    }
    return render(request, "clinic/add-review.html", context)

def submit_form_request(request, treatment_name, clinic_slug=None):
    username = request.POST.get("name")
    email = request.POST.get("email")
    phone_code = request.POST.get("phone_code")
    phone_no = request.POST.get("phone_number")
    comment = request.POST.get("comments")


    if clinic_slug or treatment_name:
        clinic_data = Clinic.objects.get(slug=clinic_slug, language=Language.objects.get(code=request.LANGUAGE_CODE), status= 'publish')
        clinic_treatment_leads_instance= ClinicTreatmentLeads.objects.create(username=username, email=email, phone_code=phone_code, 
        phone_no=phone_no, comment = comment, treatment_detail = treatment_name, clinic=clinic_data)
    else:
        clinic_treatment_leads_instance= ClinicTreatmentLeads.objects.create(username=username, email=email, phone_code=phone_code, 
        phone_no=phone_no, comment = comment, treatment_detail = treatment_name)
    clinic_treatment_leads_instance.save()


def get_free_quote(request):
    all_countries = Country.objects.filter(language=Language.objects.get(code=request.LANGUAGE_CODE)).reverse()
    context = {'all_countries': all_countries}

    global clinic
    global treatment_name
    if request.method == 'POST':
        if request.POST.get('from_search'):
            clinic = request.POST.get('clinic_slug')
            treatment_name = request.POST.get('treatment_name', '')

            return render(request, "clinic/free-quote.html", context)
            
        submit_form_request(request, clinic_slug=clinic, treatment_name=treatment_name)
        if request.LANGUAGE_CODE == 'fr':
            messages.success(request, 'Votre demande a été envoyée avec succès.')
        else:
            messages.success(request, 'Your request has been submitted successfully.')
        return redirect(request.path_info)
    
    clinic=None
    treatment_name=''

    return render(request, "clinic/free-quote.html", context)


def destinations(request, search_country="", search_city=""):
    sort_by = request.GET.get('sort_by', None)
    country = request.GET.get("country", None)
    city = request.GET.get("city", None)
    score = request.GET.get("score", 0)

    search_country = unquote(search_country)
    search_city = unquote(search_city)

    search_country = country if country else search_country
    search_city = city if city else search_city

    search_city = search_city.replace("-", " ")


    RECORDS_LIMIT = 10

    page = int(request.GET.get('page', 1))

    clinics = Clinic.objects.filter(language=Language.objects.get(code=request.LANGUAGE_CODE), city__icontains=search_city, country__name__icontains=search_country, status= 'publish')
    if sort_by=='rating':
        clinics = sorted(clinics, key=attrgetter('get_avg_rating'), reverse=True)

    # if (search_country) and (not sort_by == 'rating'):
    #     clinics = clinics.filter(country__name=search_country)
    # elif (search_country) and (sort_by == 'rating'):
    #     clinics = [cl for cl in clinics if cl.country.name == search_country]

    # if (search_city):
    #     clinics = [cl for cl in clinics if cl.city == search_city]

    all_clinics = set()
    all_countries = set()
    all_cities = set()

    for cl in clinics:
        if (float(cl.get_avg_rating) >= float(score)):
            if (search_country) :
                all_cities.add(cl.city)
            else:
                all_countries.add(cl.country)

            all_clinics.add(cl)

    clinics_for_destinations = Clinic.objects.filter(language=Language.objects.get(code=request.LANGUAGE_CODE), status= 'publish')
    for cl in clinics_for_destinations:
        if (float(cl.get_avg_rating) >= float(score)):
            if search_country:
                if cl.country.name == search_country:
                    all_cities.add(cl.city)
            else:
                all_countries.add(cl.country)
    all_clinics = list(all_clinics)

    all_clinics = all_clinics[:(RECORDS_LIMIT*page)]

    next_page = int(page) + 1

    # show next page button if next page exists
    if clinics.__len__() > (RECORDS_LIMIT*page):
        next_page_exist = True
    else:
        next_page_exist = False

    # context
    context = {
        "page": page,
        "next_page": next_page,
        "next_page_exist": next_page_exist,
        "all_clinics": all_clinics,
        "sort_by": sort_by,
        "all_countries": all_countries,
        "search_country": search_country,
        "score": score,
        "all_cities": all_cities,
        "search_city": search_city,
        "country": search_country if search_country else None,
        "is_country": search_country if search_country else None,
        "is_city": search_city if search_city else None,

    }

    return render(request, "clinic/search.html", context)



def search_clinic(request, search_treatment= "", search_country = "", search_city=""):
    sort_by = request.GET.get('sort_by', '')
    country = request.GET.get("country", "")
    city = request.GET.get("city", "")
    price = request.GET.get("price", "")
    score = request.GET.get("score", 0)

    RECORDS_LIMIT = 10

    page = int(request.GET.get('page', 1))

    search_treatment = unquote(search_treatment)
    search_country = unquote(search_country)
    search_city = unquote(search_city)


    search_country = country if country else search_country
    search_city = city if city else search_city
    
    search_city = search_city.replace("-", " ")

    if not price:
        price = f"0-{sys.maxsize}"

medicalSite/treatment/views.py
from django.shortcuts import render

# Create your views here.

medicalSite/templates/clinic/add-review.html
{% extends 'main/base.html' %}

{% load static %}

{% load i18n %}





{% block title %}MyTripMed - {% trans "Clinic Review" %}{% endblock title %}
{% block description %}{% trans "Add a review for a doctor or clinic to help other users make the right decision." %}{% endblock description %}


{% block body %}

<section class="top-section pb-0">

  <div class="container heading-border">

    <h1 class="mb-3">{% trans "Submit Review" %}</h1>

    <h5 class="text-dark">{% trans "Submit the review for the" %} {{ clinic_data.name }}</h5>

  </div>

</section>



<div class="contact-top">

</div>



<div class="container mb-5 pb-5">

  <div class="row">

    <div class="col-md-8 container-border">

      <div class="form-left card card-sm">

        <form method="POST" action="{% url 'clinics:clinics_reviews' clinic_data.slug %}">

          {% csrf_token %}

          <h4 class="text-dark mb-4">{% trans "Fill this form to submit your review" %} </h4>

          <div class="row">



            <div class="col-12">

              <h6 class="mt-2 mb-4">

                {% trans "Give your review:" %}

              </h6>



              <div class="row">

                <div class="col-md-4 col-sm-6">

                  <p class="text-grey text-700 p-sm">

                    {% trans "For Quality" %}

                  </p>



                  <div class="star-container">

                    <input type="radio" id="Qualitystar-1" value="5" name="QualityStar" required/>

                    <label for="Qualitystar-1"><i data-feather="star"></i></label>

                    <input type="radio" id="Qualitystar-2" value="4" name="QualityStar" checked/>

                    <label for="Qualitystar-2"><i data-feather="star"></i></label>

                    <input type="radio" id="Qualitystar-3" value="3" name="QualityStar" />

                    <label for="Qualitystar-3"><i data-feather="star"></i></label>

                    <input type="radio" id="Qualitystar-4" value="2" name="QualityStar" />

                    <label for="Qualitystar-4"><i data-feather="star"></i></label>

                    <input type="radio" id="Qualitystar-5" value="1" name="QualityStar" />

                    <label for="Qualitystar-5"><i data-feather="star"></i></label>

                  </div>

                </div>



                <div class="col-md-4 col-sm-6">

                  <p class="text-grey text-700 p-sm">

                    {% trans "For Service" %}

                  </p>



                  <div class="star-container">

                    <input type="radio" id="Servicestar-1" value="5" name="ServiceStar" required/>

                    <label for="Servicestar-1"><i data-feather="star"></i></label>

                    <input type="radio" id="Servicestar-2" value="4" name="ServiceStar" checked/>

                    <label for="Servicestar-2"><i data-feather="star"></i></label>

                    <input type="radio" id="Servicestar-3" value="3" name="ServiceStar" />

                    <label for="Servicestar-3"><i data-feather="star"></i></label>

                    <input type="radio" id="Servicestar-4" value="2" name="ServiceStar" />

                    <label for="Servicestar-4"><i data-feather="star"></i></label>

                    <input type="radio" id="Servicestar-5" value="1" name="ServiceStar" />

                    <label for="Servicestar-5"><i data-feather="star"></i></label>

                  </div>

                </div>



                <div class="col-md-4 col-sm-6">

                  <p class="text-grey text-700 p-sm">

                    {% trans "For Cleanliness" %}

                  </p>



                  <div class="star-container">

                    <input type="radio" id="Cleanlinessstars-1" value="5" name="CleanlinessStar" required/>

                    <label for="Cleanlinessstars-1"><i data-feather="star"></i></label>

                    <input type="radio" id="Cleanlinessstars-2" value="4" name="CleanlinessStar" checked/>

                    <label for="Cleanlinessstars-2"><i data-feather="star"></i></label>

                    <input type="radio" id="Cleanlinessstars-3" value="3" name="CleanlinessStar" />

                    <label for="Cleanlinessstars-3"><i data-feather="star"></i></label>

                    <input type="radio" id="Cleanlinessstars-4" value="2" name="CleanlinessStar" />

                    <label for="Cleanlinessstars-4"><i data-feather="star"></i></label>

                    <input type="radio" id="Cleanlinessstars-5" value="1" name="CleanlinessStar" />

                    <label for="Cleanlinessstars-5"><i data-feather="star"></i></label>

                  </div>

                </div>



                <div class="col-md-4 col-sm-6">

                  <p class="text-grey text-700 p-sm">

                    {% trans "For Comfort" %}

                  </p>



                  <div class="star-container">

                    <input type="radio" id="Comfortstar-1" value="5" name="ComfortStar" required/>

                    <label for="Comfortstar-1"><i data-feather="star"></i></label>

                    <input type="radio" id="Comfortstar-2" value="4" name="ComfortStar" checked/>

                    <label for="Comfortstar-2"><i data-feather="star"></i></label>

                    <input type="radio" id="Comfortstar-3" value="3" name="ComfortStar" />

                    <label for="Comfortstar-3"><i data-feather="star"></i></label>

                    <input type="radio" id="Comfortstar-4" value="2" name="ComfortStar" />

                    <label for="Comfortstar-4"><i data-feather="star"></i></label>

                    <input type="radio" id="Comfortstar-5" value="1" name="ComfortStar" />

                    <label for="Comfortstar-5"><i data-feather="star"></i></label>

                  </div>

                </div>



                <div class="col-md-4 col-sm-6">

                  <p class="text-grey text-700 p-sm">

                    {% trans "For Communication" %}

                  </p>



                  <div class="star-container">

                    <input type="radio" id="Communicationstar-1" value="5" name="CommunicationStar" required/>

                    <label for="Communicationstar-1"><i data-feather="star"></i></label>

                    <input type="radio" id="Communicationstar-2" value="4" name="CommunicationStar" checked />

                    <label for="Communicationstar-2"><i data-feather="star"></i></label>

                    <input type="radio" id="Communicationstar-3" value="3" name="CommunicationStar" />

                    <label for="Communicationstar-3"><i data-feather="star"></i></label>

                    <input type="radio" id="Communicationstar-4" value="2" name="CommunicationStar" />

                    <label for="Communicationstar-4"><i data-feather="star"></i></label>

                    <input type="radio" id="Communicationstar-5" value="1" name="CommunicationStar"  />

                    <label for="Communicationstar-5"><i data-feather="star"></i></label>

                  </div>

                </div>

              </div>



            </div>



            <div class="col-md-12">

              <label for="nameInput" class="form-label">{% trans "Name" %}*</label>

              <input type="text" class="form-input" placeholder="{% trans "Enter your name" %}" aria-label="First Name" id="nameInput"

                name="name" required>

            </div>





            <div class="col-md-12 mt-4">

              <label for="email" class="form-label">{% trans "Email" %}*</label>

              <input type="email" class="form-input" placeholder="{% trans "Email" %}" aria-label="Email" id="email" name="email"

                required>

            </div>



            <div class="col-12 mt-4">

              <label for="review">{% trans "Review" %}*</label>

              <textarea class="form-input" rows="4" placeholder="{% trans "Enter your review" %}" id="review"

                name="review" required></textarea>

            </div>



            <div class="col-12 mt-5 pb-3">

              <div class="d-grid gap-2 d-md-flex justify-content-md-end">

                <button class="btn btn-primary" type="submit">{% trans "Submit" %}</button>

              </div>

            </div>

          </div>



        </form>

      </div>

    </div>

  </div>

</div>

</div>



{% endblock body %}

medicalSite/templates/clinic/free-quote.html
{% extends 'main/base.html' %}

{% load static %}

{% load i18n %}





{% block title %}MyTripMed - {% trans "Request a Free Quote" %}{% endblock title %} 
{% block description %}{% trans "To find your doctor at the best price, request your free quote now and compare all the offers in a few clicks." %}{% endblock description %}
  

{% block body %}

  





<section class="top-section">

  <div class="container heading-border mb-0">

          <h1>{% trans "Request your free quote" %}!</h1>

     

        <div class="icon-text icon-text-big">

          <img src="{% static 'img/cross-icon.png' %}" alt="cross-icon">

            <span class="text-dark">{% trans "Without any fees" %}</span>

              </div>



              <div class="icon-text pt-4">

                  <h5 class="text-dark">{% trans "Save up to 70% on the treatment prices you wish to carry out. Our renowned doctors and clinics guarantee quality and unbeatable prices." %}</h5>

                </div>

          </div>

  </section>



  <div class="quote-top">

  </div>



<div class="container mb-5 pb-5">   

  <div class="row">

    <div class="col-md-8 container-border-left">

      <div class="form-left card card-sm">

        <form method= "POST" action= "" >

          {% csrf_token %}

        <h4 class="text-dark mb-4">{% trans "Free Quote" %}</h4>

          <div class="row">

            <div class="col-md-6 mt-4">

              <label for="nameInput" class="form-label">{% trans "Name" %}*</label>

            <input type="text" class="form-input"

          placeholder="{% trans "Enter your name" %}" aria-label="First Name" id="nameInput" name="name" required>

        </div>



      <div class="col-md-6 mt-4">

            <label for="emailInput" class="form-label">{% trans "Email" %}*</label>

        <input type="email" class="form-input" placeholder="{% trans "Email address" %}" aria-label="Email" id="emailInput" name="email" required>

    </div>

 

      <div class="col-xl-12 col-lg-8 pt-3">

        <label for="phoneInput" class="form-label">{% trans "Phone Number" %}*</label>

        <div class="row">

        

          <div class="col-4">

            <select class="form-select" id="phoneInput" name="phone_code" required>

              <option value="" selected disabled>{% trans "Select phone code" %}</option>

                {% for country in all_countries %}

                <option data-countryCode={{country.name}} value={{country.phone_code}}>{{country.name}} ({{country.phone_code}})</option>

                {% endfor %}

              </select>

          </div>

          <div class="col-8">

            <input type="number" class="form-input" 

            placeholder="{% trans "Enter your phone number" %}" aria-label="Enter your phone number" name="phone_number" required>

          </div>

        </div>

      </div>



      <div class="col-12 pt-3">

        <label for="commentsInput">{% trans "Message" %}*</label>

          <textarea class="form-input" 

          rows="4"

          placeholder="{% trans "Type of processing, desired destination" %}" id="commentsInput" name="comments" required></textarea>

      </div>

    

          <div class="col-12 mt-5 pb-3">

              <div class="d-grid gap-2 d-md-flex justify-content-md-end">

            <button class="btn btn-primary" type="submit">{% trans "Send" %}</button>

          </div>

        </div>

      </div>



    </form>

  </div>        

  </div>

</div>

 

    </div>

  </div>



{% endblock body %}

medicalSite/templates/clinic/treatment.html
{% extends 'main/base.html' %}
{% load static %}
{% load i18n %}


{% block title %}{% trans "All treatments: cosmetic surgery, dental, hair transplant" %} - MyTripMed{% endblock title %}
{% block description %}{% trans "Mytripmed: Find and compare prices for dental care, cosmetic surgery or hair transplantation." %}{% endblock description %}
{% block body %}

<section class="top-section pb-0">
  <div class="container heading-border">
    <h1 class="mb-3">{% trans "All Treatments" %}</h1>
  </div>
</section>

<div class="contact-top">
</div>

<div class="container mb-5 pb-5">
  <div class="row">
    <div class="col-md-12 container-border ">
      <div class="card card-sm">
        {% for treatment in treatments %}
        <p><a href='{% url "clinics:clinics_search" %}/{{treatment.slug}}' style="color: black" >{{ treatment.searched_treatment }}</a></p>
        {% endfor %}
      </div>
    </div>
  </div>
</div>
</div>


{% endblock body %}